name: Docker Image CI
on:
  push:
    branches:
      - "fraud-detection"


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
            
    - name: Build main images
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: seng660team1/dollardollar:demo

    - name: Check for Image
      run: docker image ls

    - name: Save Docker image
      run: docker save -o seng660team1-docker-image.tar seng660team1/dollardollar:demo

    - name: Archive Docker image
      uses: actions/upload-artifact@v4
      with:
        name: seng660team1-docker-image
        path: ./seng660team1-docker-image.tar
        retention-days: 7


  code-static-security-analysis:
    name: SAST - CodeQL         #static code analysis engine developed by GitHub
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   #tells the workflow to check out your repository’s code into the GitHub Actions runner

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3   #refers to a GitHub Action that initializes the CodeQL analysis process
        with:
          languages: 'python, javascript'

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3   #refers to a GitHub Action that performs the CodeQL analysis
        with:
          category: 'security'   #specifies that the analysis should focus on security issues

      - name: Upload CodeQL Python results
        uses: actions/upload-artifact@v4  #refers to a GitHub Action that uploads the results of the CodeQL analysis
        with:
          name: CodeQL Python Results
          path: /home/runner/work/dollardollar/results/python.sarif   #specifies the path to the SARIF file containing the analysis results
          retention-days: 7

      - name: Upload CodeQL JavaScript results
        uses: actions/upload-artifact@v4   #refers to a GitHub Action that uploads the results of the CodeQL analysis
        with:
          name: CodeQL JavaScript Results
          path: /home/runner/work/dollardollar/results/javascript.sarif   #specifies the path to the SARIF file containing the analysis results
          retention-days: 7


  code-dynamic-security-analysis:
    name: DAST - OWASP ZAP        
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   #tells the workflow to check out your repository’s code into the GitHub Actions runner

      - name: Wipe Docker clean
        run: docker system prune -a --volumes --force #cleans up unused Docker images, containers, networks, and volumes to free up space

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: seng660team1-docker-image
          path: ${{ runner.temp}}

      - name: Load Docker image
        run: |
          docker load --input ${{ runner.temp }}/seng660team1-docker-image.tar
          docker image ls -a

      - name: Spin Up Docker Containers
        run: docker compose -f /home/runner/work/dollardollar/dollardollar/docker-compose.yml up --detach

      - name: Wait for app to start
        run: sleep 10   #waits for 60 seconds to ensure that the application is fully started before running the ZAP scan 

      - name: Check if app is running
        run: netstat -tuln\

      - name: Probe app
        run: |
          curl http://localhost:5006 || exit 1   #checks if the application is running by sending a request to the specified URL

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:5006'

      - name: Kill Docker containers
        run: docker compose -f /home/runner/work/dollardollar/dollardollar/docker-compose.yml down
