name: Docker Image CI
on:
  push:
    branches:
      - "fraud-detection"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
            
    - name: Build main images
      if: github.ref == 'refs/heads/fraud-detection'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: seng660team1/dollardollar:demo